/*
 * Copyright (C) 2014 beatsleigher
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.m4gkbeatz.androidtoolkit.logging;

import eu.m4gkbeatz.androidtoolkit.settings.SettingsManager;

import java.io.*;
import java.util.*;

/**
 *
 * @author beatsleigher
 */
public final class Logger extends javax.swing.JFrame {
    
    SettingsManager settings = null;
    BufferedWriter writer = null;

    /**
     * Creates new form Logger
     * @param settings
     */
    public Logger(SettingsManager settings) {
        initComponents();
        this.settings = settings;
        File f = new File(System.getProperty("user.home") + "/.androidtoolkit/logs/log_" + new Date().getYear() + "_" + new Date().getMonth() + "_" + new Date().getDay() + "-" + new Random().nextInt());
        if (!f.exists()) {
            f.getParentFile().mkdirs();
            try {
            f.createNewFile();
            writer = new BufferedWriter(new FileWriter(f));
            } catch (IOException ex) {
                log(LogLevel.SEVERE, "ERROR: Error while creating new log file!\n" + ex.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Universal Android Toolkit | Log");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void log(LogLevel lvl, String log) {
        jTextArea1.append("→ " + new Date().toGMTString() + " [" + lvl + "] " + log + "\n");
        if (settings.saveLogs()) {
            try {
                writer.write("→ " + new Date().toGMTString() + " [" + lvl + "] " + log + "\n");
            } catch (IOException ex) {
                System.err.println("ERROR: Error while writing log to Logger!\n" + ex.toString());
            }
        }
    }
    
    public void close() {
        try {
            writer.close();
        } catch (IOException ex) {
            System.err.println("ERROR: Error while destroying logger!\n" + ex.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
